apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    name: myapp-2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
