Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"
  config.vm.provider :vmware_desktop do |vmware|
  config.vm.network "private_network", type: "dhcp"
    vmware.gui = true
    vmware.cpus = 2
    vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
    vmware.ssh_info_public = true
    vmware.linked_clone = false
    server.vm.provision "shell", inline: <<-SHELL
      mkdir /home/vagrant/new_ssh_keys
      ssh-keygen -t rsa -b 2048 -f /home/vagrant/new_ssh_keys/id_rsa -N ""
      cp /home/vagrant/new_ssh_keys/id_rsa /vagrant/.vagrant/server_priv_key
      cat /home/vagrant/new_ssh_keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
end


Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"
  config.vm.provider :vmware_desktop do |vmware|
  config.vm.network "private_network", type: "dhcp"
    vmware.gui = true
    vmware.cpus = 2
    vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
    vmware.ssh_info_public = true
    vmware.linked_clone = false
      cp /vagrant/.vagrant/server_priv_key /home/vagrant/server_priv_key
    SHELL

  end
end